# FROM python:3.9.10-bullseye
FROM python:bullseye

WORKDIR /app

ARG TEST_ENV=local_repo

COPY requirements.txt requirements.txt
COPY developer_requirements.txt developer_requirements.txt

COPY . .

RUN pip install -r developer_requirements.txt
RUN if [ "$TEST_ENV" = "local_repo" ] ; then pip install -r requirements.txt ; else echo "TEST_ENV not local_repo, don't install package requirements" ; fi
RUN if [ "$TEST_ENV" = "local_publish" ] ; then cd publish && sh ./publish_local.sh ; else echo "TEST_ENV not local_publish, don't build the package locally" ; fi

CMD [ "python", "-m" , "pytest"]