# FROM python:3.9.10-bullseye
FROM python:bullseye

WORKDIR /app

ARG PYPI_REPO_USER=NOTGIVEN
ARG PYPI_REPO_PASS=NOTGIVEN

COPY requirements.txt requirements.txt
COPY developer_requirements.txt developer_requirements.txt

COPY . .

RUN python -m pip install -U pip
RUN pip install -r developer_requirements.txt
RUN pip install twine
RUN cd publish && sh ./publish_remote.sh --use_tag -f
RUN pip install sjournal


CMD [ "python", "-m" , "pytest", "--test_environment=remote_publish"]